# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-10-16

version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"
        
    sensation-geolocator:
        image: ${IMAGE}
        depends_on:
            - odsupercomponent
        network_mode: host
        command: "/opt/opendlv.cfsd18/bin/opendlv-logic-cfsd18-sensation-geolocator --cid=${CID} --freq=20"
#    proxy-ellipse2n:
#        image: "ellipseproxy:ellipsev0.0.2"
#        network_mode: "host"
#        ipc: host
#        devices:
#            - "/dev/ttyUSB0:/dev/ttyUSB0"
#        command: "opendlv-proxy-ellipse2n --cid=120 --id=112"

    odcockpit:
       image: ${IMAGE}
       network_mode: host
       environment:
       - DISPLAY=$DISPLAY
       volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix
       - .:/opt/opendlv.data
       - ~/recordings:/opt/recordings
       ipc: host
       user: odv
       depends_on:
           - odsupercomponent
       command: "/opt/od4/bin/odcockpit --cid=${CID}"
