version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    # microservice for perception-detectcone
    logic-cfsd18-perception-detectcone:
        image: ${IMAGE}
        depends_on:
            - odsupercomponent
        ipc: host
        user: odv
        network_mode: host
        command: "/opt/opendlv.cfsd18/bin/opendlv-logic-cfsd18-perception-detectcone --cid=${CID} --id=1"
    # microservice for cfsd18-sensation-attention
    cfsd18-sensation-attention:
        image: ${IMAGE}
        network_mode: "host"
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv.cfsd18/bin/opendlv-logic-cfsd18-sensation-attention --cid=${CID} --verbose=1 --id=1"
    #proxy-velodyne16
    velodyne16:
        image: ${IMAGE}
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        ipc: host
        user: odv
        working_dir: "/opt/opendlv.data"
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-velodyne16 --cid=${CID}"
    proxy1:
        image: ${IMAGE}
        network_mode: host
        depends_on:
            - odsupercomponent
        group_add:
            - video
        ipc: host
        user: odv
        devices:
            - "/dev/video0:/dev/video0"
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-camera --cid=${CID}  --id=1 --freq=20"

