os: linux
language: cpp
sudo: required
branches:
  only:
  - cognition.main
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - DOCKERHUB='ziwei000'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: p7dk5TI8liqVX4DvcbZiHwA/wF2XnTSyje7osXK3qDFJct8CPQINC3+wcoTFHyAOH3R45UJPPk3t2weEnrn0uLQKg2mEsl6wdrusvOH8z2lLmdcR/RobgT1Guqazc7/Wmj4vyNwj/l39bpqzU2oIn8ivOuT+SXizOdVDSfjjvQvNjyWtOSGPgB/8EcHPbgAG7H0fNNoc4WlKBbseaj6wVMJW2tffHhAIveK+mdIKOfMou9gOtYnEhAOrLVLw9dvsIL7FYpr8pKiL/lWQnu4YlUOBE5WbPa5gIZO4ZLuXszXGwlVt4W/fYzXo4Iy16XMQ5qGnjwhhrSUAYXn9uL/kJ7HgnwchGrvTFEVtxkRRSWYed33Zvl9Qe5cpzUeLxvrTlDp/ZdfCg4eRCXPQ6HuLg/vgraGy4KzHVNGLVgetckY3zn+2fg87EX5AgKn3C9bMBLzRM9yHpvKa2ZMAp5vmoJn7Cwt1KQ0d2I9K91lj+8Waz+Y9ferrOHjXjsTE0/NaSFkEJnjYM2HG+vI3AOQ9NFjoIp67TO34R8uZu6OC/7yPDKqrOnk8cs++LCunScfEJvKmj77cOYr69hpegNIvPRpIazWTVHZQ55KEpFKyCmPXNP1H3e5W/qpOAwlUd0Q+jLsw3iVRGErr5oujpCkxqEDIAFBVKNJFyHD7qG4FCV8=
  - secure: jmKvjZn+xp6PmKgS8XJs+9GsSfIlXEnRKsyKhIeKcgKnzXnajNZGoR0bkQdi4yVj9oyvIzEBIiDLzZfga/xv/2Qh1ZwOtxDDMMJyF8bBQB6iGRNJuBp7NcN0v0OORQygR01gYB6PlUVmH0wUtSVWO0b1DMe8rhGdoUQrSwGjpCK7fdd09QgtJsZ5io3gEyZaO8PcEpAwI8gxykjYZnAha7L2bedLyx32e5phh732+m3kM0zASOcmMd8vj4PauBqTGDcS410Rro5L8BlcqptyafwX/v0Qo5mfNZPmUEe2Y3VwrpWToYWo60HYE6h8y2L6nFiq37fDMFNec+0P0ouCXedBt46P1FYYl2cV6MfiID2Py5UFuGQ5dcxFu+BJHKkL6uwx0ClOqP65FgHt59Zbu8KRFRrEPiEdXy5J1My8/bKAOchcPGsbONHhmYIjGvnmrqvMDazBzzJUtnke/MWpF5CP2oxzPSGW2G0nGXSYh9JZ35o4wQ4etw6nk3hV8svgJqVIf49u2EtF9zgMt+P2ZvUaVIgja+R7pL7oHLqP0gNsLyePuI4o3Gd7EF0V1GZnmToC9xhPj0RHJq8XsqinWb//z7lAQxpWOQFnhjP6S+pYs7Ow6MB+jxYyT8FJs9z5659Te6BljgxcBkxJThkI7LtMp9VahhanlXbelkfH6mw=
install:
- cd docker
- make buildComplete createDockerImage
- docker tag seresearch/opendlv-cfsd18-on-opendlv-core-on-opendavinci-on-base:latest ${IMAGE}:${COMMIT}
script: skip
after_success:
- docker --version
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker tag ${IMAGE}:${COMMIT} ${DOCKERHUB}/${IMAGE}:${COMMIT}
- docker push ${DOCKERHUB}/${IMAGE}:${COMMIT}
notifications:
  email:
    on_success: never
    on_failure: never
